amnesty_app/config/routes.rb
AmnestyApp::Application.routes.draw do
  resources :amnesties


  get "static/index"

  resources :amnesties
  root :to => 'static#index'
end

amnesty_app/app/models/amnesty.rb
# == Schema Information
#
# Table name: amnesty
#
#  id              :integer          not null, primary key
#  category        :text
#  body            :text
#  issue_date      :text
#  data_id         :text
#  gender          :text
#  all_dates       :text
#  year            :integer
#  appeal_date     :text
#  year_case_count :text
#  iso3            :text
#  country         :text
#  action          :text
#  document        :text
#  subject         :text
#

class Amnesty < ActiveRecord::Base
	set_table_name 'amnesty'
  attr_accessible :category, :body, :issue_date, :gender, :all_dates, :year, :year_case_count, 
  	:iso3, :country, :action, :document, :subject
end

amnesty_app/app/controllers/amnesties_controller.rb
class AmnestiesController < ApplicationController
  # GET /amnesties
  # GET /amnesties.json
  def index
    @amnesties = Amnesty.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @amnesties }
    end
  end

  # GET /amnesties/1
  # GET /amnesties/1.json
  def show
    @amnesty = Amnesty.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @amnesty }
    end
  end

  # GET /amnesties/new
  # GET /amnesties/new.json
  def new
    @amnesty = Amnesty.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @amnesty }
    end
  end

  # GET /amnesties/1/edit
  def edit
    @amnesty = Amnesty.find(params[:id])
  end

  # POST /amnesties
  # POST /amnesties.json
  def create
    @amnesty = Amnesty.new(params[:amnesty])

    respond_to do |format|
      if @amnesty.save
        format.html { redirect_to @amnesty, notice: 'Amnesty was successfully created.' }
        format.json { render json: @amnesty, status: :created, location: @amnesty }
      else
        format.html { render action: "new" }
        format.json { render json: @amnesty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /amnesties/1
  # PUT /amnesties/1.json
  def update
    @amnesty = Amnesty.find(params[:id])

    respond_to do |format|
      if @amnesty.update_attributes(params[:amnesty])
        format.html { redirect_to @amnesty, notice: 'Amnesty was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @amnesty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amnesties/1
  # DELETE /amnesties/1.json
  def destroy
    @amnesty = Amnesty.find(params[:id])
    @amnesty.destroy

    respond_to do |format|
      format.html { redirect_to amnesties_url }
      format.json { head :no_content }
    end
  end
end

amnesty_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

amnesty_app/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

amnesty_app/app/helpers/amnesties_helper.rb
module AmnestiesHelper
end

amnesty_app/app/helpers/application_helper.rb
module ApplicationHelper
end

amnesty_app/app/helpers/static_helper.rb
module StaticHelper
end

amnesty_app/app/views/amnesties/_form.html.erb
<%= form_for @amnesty do |f| %>

  <%= f.label :category %>      
 	<%= f.text_field :category %><br />

 	<%= f.label :issue_date, "Issue Date" %>
 	<%= f.text_field :issue_date, class: 'issue_datepicker' %><br />

 	<%= f.label :gender %>
  <%= f.select :gender, %w[Male Female] %><br />
  
  <%= f.label :all_dates %>
  <%= f.text_field :all_dates %><br />
 
  <%= f.label :year %>
  <%= f.text_field :year %><br />
  
  <%= f.label :year_case_count %>
  <%= f.text_field :year_case_count %><br />
  
  <%= f.label :iso3 %>
  <%= f.text_field :iso3 %><br />
  
  <%= f.label :country %>
  <%= f.country_select :country, ["United States"] %><br />
  
  <%= f.label :action %>
  <%= f.text_field :action %><br />
  
  <%= f.label :document %>
  <%= f.text_field :document %><br />
  
  <%= f.label :subject %>
  <%= f.text_field :subject %><br />

  <%= f.submit 'Save' %>
<% end %>

amnesty_app/app/views/amnesties/_form.html.haml
= form_for @amnesty do |f|
  - if @amnesty.errors.any?
    #error_explanation
      %h2= "#{pluralize(@amnesty.errors.count, "error")} prohibited this amnesty from being saved:"
      %ul
        - @amnesty.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

amnesty_app/app/views/amnesties/edit.html.haml
%h1 Editing amnesty

= render 'form'

= link_to 'Show', @amnesty
\|
= link_to 'Back', amnesties_path

amnesty_app/app/views/amnesties/index.html.haml
%h1 Listing amnesties

%table
  %tr
    %th
    %th
    %th

  - @amnesties.each do |amnesty|
    %tr
      %td= link_to 'Show', amnesty
      %td= link_to 'Edit', edit_amnesty_path(amnesty)
      %td= link_to 'Destroy', amnesty, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Amnesty', new_amnesty_path

amnesty_app/app/views/amnesties/new.html.haml
%h1 New amnesty

= render 'form'

= link_to 'Back', amnesties_path

amnesty_app/app/views/amnesties/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_amnesty_path(@amnesty)
\|
= link_to 'Back', amnesties_path

amnesty_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmnestyApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript" src="http://mbostock.github.io/d3/talk/20111018/d3/d3.js"></script>
  <script type="text/javascript" src="populations.js"></script>
  <script type="text/javascript" src="http://mbostock.github.io/d3/talk/20111018/d3/d3.geo.js"></script>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>